// <auto-generated />
using System;
using ChangelogProject.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChangelogProject.Migrations {
	[DbContext(typeof(DataContext))]
	partial class DataContextModelSnapshot : ModelSnapshot {
		protected override void BuildModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
			modelBuilder
					.HasAnnotation("ProductVersion", "6.0.4")
					.HasAnnotation("Relational:MaxIdentifierLength", 63);

			NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

			modelBuilder.Entity("ChangelogProject.Infra.Models.Client", b => {
				b.Property<string>("Id")
						.HasColumnType("text");

				b.Property<DateTime>("CreatedAt")
						.HasColumnType("timestamp with time zone");

				b.Property<string>("CreatedBy")
						.IsRequired()
						.HasColumnType("text");

				b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("text");

				b.Property<DateTime>("UpdatedAt")
						.HasColumnType("timestamp with time zone");

				b.Property<string>("UpdatedBy")
						.IsRequired()
						.HasColumnType("text");

				b.HasKey("Id");

				b.ToTable("Clients");
			});
#pragma warning restore 612, 618
		}
	}
}
